In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[
    'I have a name',
    'the glass of juice',
    'the glass of water',
    'your video not good',
    'developer is no more'
]

In [3]:
voc_size=10000
one_repr=[one_hot(words,voc_size) for words in sent]
one_repr

[[9038, 4206, 257, 8659],
 [8986, 2682, 950, 5596],
 [8986, 2682, 950, 633],
 [4423, 5234, 2756, 3897],
 [4733, 7577, 3922, 8112]]

In [7]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
import numpy as np


In [8]:
sent_length=7
emb=pad_sequences(one_repr,padding='pre',maxlen=sent_length)
print(emb)

[[   0    0    0 9038 4206  257 8659]
 [   0    0    0 8986 2682  950 5596]
 [   0    0    0 8986 2682  950  633]
 [   0    0    0 4423 5234 2756 3897]
 [   0    0    0 4733 7577 3922 8112]]


In [9]:
model=Sequential()
dim=6
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [10]:
model.predict(emb[0])

1/1 [==============================] - 0s 113ms/step


array([[-0.00151192, -0.02859162, -0.03021293, -0.04918867,  0.03818699,
        -0.02820531],
       [-0.00151192, -0.02859162, -0.03021293, -0.04918867,  0.03818699,
        -0.02820531],
       [-0.00151192, -0.02859162, -0.03021293, -0.04918867,  0.03818699,
        -0.02820531],
       [ 0.02585609,  0.01375725, -0.02139815,  0.02872025,  0.04844007,
        -0.02351813],
       [ 0.02908036, -0.01338979,  0.01778109, -0.00186844,  0.04235332,
        -0.00918873],
       [-0.0159898 , -0.001128  , -0.01427723,  0.01040319,  0.04726357,
        -0.0042555 ],
       [-0.00127007,  0.00299623,  0.03860451,  0.03740411,  0.03268137,
        -0.00193126]], dtype=float32)

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 7, 6)              60000     
                                                                 
Total params: 60000 (234.38 KB)
Trainable params: 60000 (234.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
